language: python
env:
    - PYVERSION="2.7"   NENGINES=1
    - PYVERSION="2.7"   NENGINES=9
    - PYVERSION="3.3"   NENGINES=9
    - PYVERSION="3.4"   NENGINES=9
before_install:
    - sudo add-apt-repository -y ppa:andrikos/ppa
    - sudo apt-get update
    - if [[ "$PYVERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$PYVERSION setuptools pip numpy=1.8.2 pyzmq ipython matplotlib cython sphinx mock coverage requests pyyaml mpi4py
    - source activate test-environment
    - python -c "import numpy; print('Numpy version', numpy.__version__)"
    - pip install sphinxcontrib-programoutput coveralls
    - pip install pelican
    - sudo apt-get install libhdf5-mpich2-7 libhdf5-mpich2-dev  # from Nick Andrik's PPA
    - CC=mpicc pip install git+https://github.com/h5py/h5py.git@2.2.1 --install-option="--mpi"
install:
    - python setup.py install  # build DistArray
    - (cd $TRAVIS_BUILD_DIR/docs/sphinx && make html)  # build docs
    - (cd $TRAVIS_BUILD_DIR/docs/www && make html)  # build docs
before_script:
    - "export DISPLAY=:99.0"  # for plotting.py
    - "sh -e /etc/init.d/xvfb start"  # for plotting.py
    - (cd $TRAVIS_BUILD_DIR && dacluster start -n$NENGINES)
    - lsof | grep python | wc -l
script:
    - (cd $TRAVIS_BUILD_DIR && make test_with_coverage)
after_script:
    - lsof | grep python | wc -l
    - (cd $TRAVIS_BUILD_DIR && dacluster stop)
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == "3.4" && $NENGINES -eq 9 ]] ; then echo "coverage combine"; coverage combine; fi
    - if [[ $TRAVIS_PYTHON_VERSION == "3.4" && $NENGINES -eq 9 ]] ; then echo "coveralls"; coveralls; fi
